launchdarkly/ld-find-code-refs

- CHANGELOG.md
- Makefile
- README.md
- parse/internal/ld/ld.go
- parse/internal/options/options.go
- parse/parse.go
Alters the `updateSequenceId` parameter to be optional. If not provided (or set to a number < 0), data will always be updated. If provided, data will only be updated if the existing `updateSequenceId` is less than the new.
> Make update seq id optional

- CHANGELOG.md
- parse/parse.go
- parse/parse_test.go
Flags with really short keys like `a` or `ab` end up generating many
false positives, drowning out real code references with noise. For now
we will just not support those flags for code references.
I wonder if we should allow users to override this minimum with a CLI param? I'm leaning towards waiting for if/when someone requests that feature.
TODO:
> Don't grep for flags with short keys.

- parse/internal/options/options.go
This snuck in with one of the recent PRs. We missed it because the option parser does a lot of type assertions.
> Fix type of default contextLines option

- parse/internal/git/git.go
This is a must for the downstream parsing code to work properly.
> Use case sensitive ag search.

- parse/parse.go
I've tested all these limits by cranking them down and running the command against SupportService.
Note that we can't actually calculate the upper bound payload limit from these numbers because size will depend on number of flags.
https://app.clubhouse.io/launchdarkly/story/27365/add-a-minimum-character-limit-for-flags-scanned-by-the-git-flag-parser-and-other-limits
> Limit number of files, and number of hunked lines per file/flag pair.

- build/package/bitbucket-pipelines/Dockerfile
- build/package/cmd/Dockerfile
- build/package/github-actions/Dockerfile
Now that we removed the `cloneEndpoint` parameter, we no longer need the dependency on openssh. So, let's remove it.
> remove dependency on openssh

- README.md
- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/circleci/orb.yml
- build/package/github-actions/github-actions.go
- internal/git/git.go
- internal/options/options.go
- pkg/parse/parse.go
This PR removes the `repoHead` command line argument in effort to simplify the utility. 
Added new logic to infer the branch name using a special `git rev-parse` flag.
> Infer current branch checkout, remove repoHead arguments

- README.md
- build/package/circleci/orb.yml
- internal/options/options.go
Sets the default context lines count to 2. So, context lines are now opt-out.
Will follow-up this PR with doc updates.
> set default contextLines to 2

- CHANGELOG.md
- build/package/cmd/Dockerfile
Readd the openssh dependency for the base docker image in case any consumers require ssh for cloning their git repository
> add openssh dependency to CLI docker image

- CHANGELOG.md
- README.md
- internal/git/git.go
- pkg/parse/parse.go
Makes the CLI much more ergonomic as typing out the absolute path can be annoying.
Adds another error check - does the directory exist. Without this error check you get a generic error message from git when you try to get the branch name which was confusing.
```
../ld-find-code-refs/out/ld-find-code-refs -dir . -repoName=victest -projKey coderefs -accessToken api-d78ecb83-861d-4a27-ac83-5b68dca265eb -baseUri http://localhost
INFO: 2019/01/24 16:58:42 parse.go:69: absolute directory path: /Users/victor/src/go/src/github.com/launchdarkly/gonfalon
DEBUG: 2019/01/24 16:58:42 git.go:32: identified branch name: master
DEBUG: 2019/01/24 16:58:42 git.go:42: identified sha: edf1f7cc66e3cb893ca52a4ba7f87c6f599cfc8f
DEBUG: 2019/01/24 16:58:42 client.go:344: [DEBUG] GET …
```
> Allow passing relative paths for -dir parameter

- CHANGELOG.md
- README.md
- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/github-actions/github-actions.go
- cmd/ld-find-code-refs/main.go
- internal/ld/ld.go
- internal/ld/ld_test.go
- internal/log/log.go
- internal/options/options.go
- pkg/parse/parse.go
Adds the optional `debug` command line argument. If enabled, enables debug logging. The pretty-printed table of flag keys to ref counts now requires debug logging to be printed.
> Add debug command-line argument

- CHANGELOG.md
- internal/command/command.go
This will eliminate a couple of cases of false positive matches, namely: 
- when either end of the flag key has a letter or number
- when either end of the flag key has an underscore.
It'l still match when `-`, `.`, and any other punctuation on either end. I think optimizing this behavior is a rabbit hole for now so we should stick with easy `\b`. 
**Note:** For this change to have maximum impact, we should update frontend highlighting code to use the same regex.
I've QA'd this on a number of our internal repos and confirmed there aren't any regressions (to the best of my knowledge).
> Wrap flag keys in word boundary characters.

- .circleci/config.yml
- .goreleaser.yml
- CHANGELOG.md
- README.md
- build/package/circleci/orb.yml
Use goreleaser to generate deb and rpm packages.
**Note 1:** Goreleaser lets us specify deb/rpm dependencies. I tried to specify ag as a dependency, but was not able to get the install working correctly. Deb dependencies assume you're installing with a package manager, `dpkg` can't install `ag` for you. I saw a fixup command online (`apt-get install -f`) thats supposed to find broken dependencies and install them for you, but it didn't work in my test. It just tried to delete `ld-find-code-refs`. So the installation instructions for linux will specify to `apt-get install silversearcher-ag` (and whatever the appropriate install command is for yum). Or maybe just link to ag's linux install instructions.
**Note 2:** The ubuntu shell script in the readme won't work as is because github's …
> Generate deb and rpm packages.

- .goreleaser.yml
will open a PR to retroactively fix 0.5.0 in our homebrew-tap
> http -> https when goreleasing to brew

- CHANGELOG.md
- build/package/circleci/orb.yml
This PR implements some feedback from the Circle team about our orb:
- Add a link back to our docs in the root description
- Don't map to env
- Remove executor, inlining the `ld-find-code-refs` docker image spec and command into the job
- Add several usage examples
Other tweaks:
- Fixed a couple typos
- Added configurable `access_token` parameter, which is the `LD_ACCESS_TOKEN` by default.
- Added `debug` parameter
> Simplify circle orb config, add usage examples

- CHANGELOG.md
- RELEASING.md
- internal/ld/ld.go
- internal/log/log.go
- internal/options/options.go
- internal/version/version.go
- pkg/coderefs/coderefs.go
`ld-find-code-refs` will now always log the current version number to stdout. If the `version` argument is provided, `ld-find-code-refs` will immediately terminate after logging the version number.
> add version command line argument

- CHANGELOG.md
- internal/ld/ld.go
- internal/options/options.go
- pkg/coderefs/coderefs.go
changes internal behavior to send the default branch on the repo rep instead of as a `is_default` boolean on the branch rep.
> move default branch field to repo rep

- CHANGELOG.md
- pkg/coderefs/coderefs.go
This PR adds a helper log message in case we run into an error generating hunks. This shouldn't ever happen, but if it does, this log will help us debug any potential issues.
> log an error when no hunks were made for a reference

- CHANGELOG.md
- RELEASING.md
- build/package/circleci/orb.yml
- internal/version/version.go
- Added a new command line argument, `version`. If provided, the current `ld-find-code-refs` version number will be logged, and the scanner will exit with a return code of 0.
- The `debug` option is now available to the CircleCI orb.
- Added support for parsing `.ldignore` files specified in the root directory of the scanned repository. `.ldignore` may be used to specify a pattern (compatible with the `.gitignore` spec: https://git-scm.com/docs/gitignore#_pattern_format) for files to exclude from scanning.
- The internal API for specifying the default git branch (`defaultBranch`) has been changed. The `defaultBranch` argument on earlier versions of `ld-find-code-refs` will no longer do anything.
- `ld-find-code-refs` will no longer error out if an unknown error occurs when scanning for …
> Prepare 0.6.0

- CHANGELOG.md
- internal/options/options.go
The `dir` command line option was marked as optional, but is actually required. This should not be a breaking change, because the CLI would fail on execution if a `dir` was not provided.
> make dir argument required

- .goreleaser.yml
- CHANGELOG.md
- README.md
- internal/command/command.go
- internal/command/windows.go
- Adds support for windows by conditionally executing a slightly different `ag` command when running on `GOOS=windows`.
- Adds a windows build to `.goreleaser.yml`
> add windows support

- CHANGELOG.md
- build/package/circleci/orb.yml
- internal/version/version.go
- Added support for Windows. `ld-find-code-refs` releases will now contain a windows executable.
- Added a new option `-delimiters` (`-D` for short), which may be specified multiple times to specify delimiters used to match flag keys.
- The `dir` command line option was marked as optional, but is actually required. `ld-find-code-refs` will now recognize this option as required.
- `ld-find-code-refs` was performing extra steps to ignore directories for files in directories matched by patterns in `.ldignore`. This ignore process has been streamlined directly into the search so files in `.ldignore` are never scanned.
- The command-line [docker image](https://hub.docker.com/r/launchdarkly/ld-find-code-refs) now specifies `ld-find-code-refs` as the entrypoint. See our …
> Prepare 0.7.0

- README.md
Adds a small blurb in the "Execution via CLI" section which clarifies that `ld-find-code-refs` should be configured to run automatically.
> clarify execution via cli docs

- CHANGELOG.md
- internal/command/command.go
- internal/ld/ld.go
- internal/ld/ld_test.go
- pkg/coderefs/coderefs.go
- pkg/coderefs/coderefs_test.go
This PR adds new functionality to `ld-find-code-refs`. The scanner will now search for "stale" branches and delete the connection to that branch from LaunchDarkly.
A branch is stale if it does not exist on the Git remote of the currently selected branch. 
If the scanner fails to find or delete stale branches, it will continue with the scan (not a fatal error)
> Delete stale branches

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- build/package/circleci/orb.yml
- internal/version/version.go
Releases the new branch garbage collection feature.
This PR includes some quality-of-life changes to the readme (recommend reading readme changes with whitespace changes turned off)
> Prepare 1.1.0

- CHANGELOG.md
- internal/version/version.go
- pkg/coderefs/coderefs.go
- pkg/coderefs/coderefs_test.go
We currently match against delimiters when performing the coderefs search against a repository, but don't validate the delimiters later on when we pick out specific flag keys in a given line. This PR makes sure we always match against delimiters when comparing flag keys against lines.
> Always apply delims

- .circleci/config.yml
- README.md
- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/github-actions/github-actions.go
- pkg/coderefs/coderefs.go
- Clarifies language used in logging to address the concerns brought up in #98 
- Only use the fatal logger (with support CTA message) for internal fatal errors
> Logging cleanup

- CHANGELOG.md
- build/package/circleci/orb.yml
- internal/command/command.go
- internal/command/git.go
- internal/version/version.go
- pkg/coderefs/coderefs.go
- Fixed a regression causing no references to be found when a relative path is supplied to `dir`
> always convert relative repo path to absolute path

- build/package/circleci/orb.yml
Display a link to your home page and the orb source natively in the Orb registry as a clickable link.
> Add Home URL and Source Code URL

- CHANGELOG.md
- Makefile
- RELEASING.md
- Adds 1.5.0 entry to the changelog (link will 404 until https://github.com/launchdarkly/ld-find-code-refs/pull/110) is merged
- Adds a new env variable for releasing prerelease builds
> prepare 1.5.0-beta1

- Makefile
- RELEASING.md
- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/github-actions/github-actions.go
- internal/options/options.go
Fixes the release job to make sure we release to all destinations when running `publish-all`
Makes sure all wrappers support aliases
This code is already including with the 1.5.0-beta1 release.
> alias fixes for command line wrappers

- README.md
- internal/options/alias.go
This frees up the `.launchdarkly` directory namespace for potential future usage.
> rename coderefs.yaml to config.yaml

- README.md
- internal/helpers/helpers.go
- internal/options/alias.go
- pkg/coderefs/alias.go
- pkg/coderefs/alias_test.go
- pkg/coderefs/coderefs.go
Replaces the `path` options with `paths`, an array of globs. This allows for more succinct declaration of alias search.
> support glob patterns for filePattern alias matching

- internal/options/options.go
My last change in https://github.com/launchdarkly/ld-find-code-refs/pull/112 inadvertently broke configuration via CLI. For now, let's duplicate the yaml read logic in both `Init` and `Populate`-- moving the configuration format to viper later on will make this code easier to read and less prone to error.
> check for yaml configuration when initializing cli options

- README.md
- internal/options/alias.go
- internal/version/version.go
Includes some readme improvements. Code changes do not break 1.5.0-beta2 functionality, so these changes will be included by overwriting 1.5.0-beta2.
> Make alias config type field case insensitive

- README.md
- internal/options/alias.go
- internal/version/version.go
- pkg/coderefs/alias_test.go
This PR adds support for specifying multiple patterns per filepattern configuration by specifying multiple `patterns` in a list, instead of a single `pattern`. This PR also removes the obsolete `pattern` and `path` config options.
Before:
```
aliases:
- type: filepattern
files: 
- test.go
pattern: "FLAG_KEY"
```
After:
```
aliases:
- type: filepattern
files: 
- test.go
patterns: 
- "(FLAG_KEY)"
```
> Support specifying multiple alias patterns

- Makefile
reduces binary size by ~20% by omitting debug information from builds
ref: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
> update build commands to reduce binary size

- .gitignore
- CHANGELOG.md
- README.md
- cmd/ld-find-code-refs/main.go
- docs/CONFIGURATION.md
- docs/EXAMPLES.md
- internal/git/git.go
- internal/ld/ld.go
- internal/options/flags.go
- internal/options/options.go
- pkg/coderefs/coderefs.go
- Added support for scanning non-git repositories. Use the `--revision` flag to specify your repository version number. Setting this disables automatic branch pruning as ld-find-code-refs does not have a remote repository to generate a list of branches from.
- Added the `prune` sub-command to delete stale code reference data from LaunchDarkly manually by providing a list of branch names as arguments. example: `ld-find-code-refs prune [flags] branch1 branch2`
> Support scanning for coderefs for non-git codebases

- internal/search/files.go
- internal/search/files_test.go
- internal/search/testdata/symlink
Symlinks may be present in a repository, but typically should not be
processed as they may point to non-existent files (depending on the run
context) or other files in the same repository (which will be processed
independently).
> Don't process symlink contents

- CHANGELOG.md
- build/package/circleci/orb.yml
- internal/search/files.go
- internal/search/files_test.go
- internal/search/testdata/symlink
- internal/version/version.go
- Fixes a bug causing `ld-find-code-refs` to scan non-regular files, like symlinks. Thanks @d3d-z7n!
> prepare 2.0.1

- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/bitbucket-pipelines/bitbucket-pipelines_test.go
- build/package/github-actions/github-actions.go
- build/package/github-actions/github-actions_test.go
[Escalated support ticket here.](https://app.clubhouse.io/launchdarkly/story/99331/support-escalation-setting-up-multiple-yaml-files-in-coderef-works-only-intermittently)
[Slack thread here.](https://launchdarkly.slack.com/archives/C4LUP9NPM/p1611795592035000?thread_ts=1611789046.030400&cid=C4LUP9NPM)
This PR then implements the solution agreed above on slack. In order to support monorepos, we expose repoName in our github action config yaml so a single repo can map to multiple projects.
If this is approved, I'll go ahead and submit a PR for the corresponding [documentation page.](https://docs.launchdarkly.com/home/code/github-actions)
> [ch99331] Support repoName in Github action yaml

- build/package/bitbucket-pipelines/bitbucket-pipelines_test.go
- build/package/github-actions/github-actions_test.go
[ch](https://app.clubhouse.io/launchdarkly/story/105727/fix-broken-internal-options-imports-in-tests)
The `options` package were moved up one level by a separate pr and this was not caught/resolved in my earlier pr. So this ticket fixes these import statements in the github action and bitbucket test files.
> [ch105727] Fix broken import statements in tests

- .circleci/config.yml
- docs/TESTING.md
- go.mod
- go.sum
- update build to use [latest go1.17](https://go.dev/blog/go1.17)
---
relates to Homebrew/homebrew-core#83413
> build: bump to use go1.17

- search/matcher.go
- search/matcher_test.go
- search/search_test.go
sc119754
* Update Code References so it only builds the map of delimiters a single time instead of repeatedly when scanning each line for flags.
Updated test and added a new test for private function.
> Build map of delimiters once

- build/package/circleci/orb.yml
- build/package/github-actions/github-actions.go
- build/package/github-actions/github-actions_test.go
- coderefs/coderefs.go
- docs/CONFIGURATION.md
- internal/git/git.go
- options/flags.go
- options/options.go
Allow tags to be used as "branches"
1. When `--branch` is not set, and repo is in detached HEAD state, will detect a tag as a fallback
2. In github actions a `refs/tags/xxx` `GITHUB_REF` will be parsed as valid
--
too use run command with `--allowTags` or `--allowTags=true`
This resolves issue #155
> Support tags as "branch" name in coderefs

- internal/ld/ld.go
We do not need all of the environments returned when scanning for flags. This updates the query to first fetch a valid environment in the Project, then use that for subsequent requests.
> Filter flags to a single environment

- aliases/alias.go
- aliases/alias_test.go
If a directory or file does not exist in part of the Alias config FilePattern we should return an error.
> Add nil check on Alias Path and test coverage

- internal/validation/validation.go
- internal/validation/validation_test.go
- options/options.go
Adds basic validation of subdirectories via checking the directory is valid, and also making sure there are no preceding characters on the path such as `/`.
> Add validation for subdirectories of projects

- internal/ld/ld.go
- search/search.go
- search/search_test.go
Use git's underlying functionality to generate a consistent hash of the the lines of content across runs.
> Generate Hash of contents

- coderefs/coderefs.go
- internal/git/git.go
- internal/ld/ld.go
This is functionally the same as the current implementation for getting time but changed to use `int64` as it matches how Extinctions track their current time: https://github.com/launchdarkly/ld-find-code-refs/blob/master/internal/git/git.go#L243
> match Extinction time rep

- .ldrelease/install-circleci.sh
- .ldrelease/publish-circleci.sh
- .ldrelease/publish.sh
- .ldrelease/secrets.properties
- Makefile
Note that the prerequisite of this work is having a github owner circleci token. There is a [security review](https://launchdarkly.atlassian.net/browse/SEC-773) for this. In the meantime to test this, we can a dev version of the orb.
This pr migrates existing Circleci shell commands to built-in releaser steps:
1. (Done in past pr) Modify`update-version.sh` to update version numbers in circleci/orb.yml.
2. Modify `publish.sh` to install the circleci cli
3. Modify `publish.sh` to run circleci setup authenticating with a circleci token that has the github owner role.
4. Modify `publish.sh` to run circleci orb publish
> [sc-133063] Automate circleci orb publishing

- build/metadata/bitbucket/README.md
- build/metadata/github-actions/action.yml
- build/package/circleci/orb.yml
- docs/CONFIGURATION.md
Add information that `projKey` is no longer required if using `projects` block.
> Update integrations metadata

- .ldrelease/publish-circleci.sh
- .ldrelease/publish.sh
We've got our github owner token finally! Yay! This ticket is to fix a few issues found when publishing to circleci orbs using the new token:
* Fix ldreleaser path to the install cli script
* Uncomment production publish step
* Comment dev publish step
* Fix paths to other marketplace publish scripts
> [sc-136606] Circleci publishing fixes

- internal/ld/ld.go
The current retries, try with a timed exponential backoff. If a branch has multiple commits that finish at roughly the same time this will cause them to all POST at the same time and if it errors to keep retrying in sync. This will cause them to have more variation between attempts. We still perform server side validation that the highest sync time is what is used.
> Switch to use jitter with min/max

- docs/CONFIGURATION.md
Add some more details around what version supports `projects` and what's required when you're looking to use it.
> Updating Project configuration docs for upgrade requirements

- coderefs/coderefs.go
- internal/ld/ld.go
To perserve backwards compatibility we're using the 1st project key in the CSV filename output. If a user is still using `projKey` it is convert to the 1st and only project.
> Use first project key in filename output

- .goreleaser.yml
- Makefile
* Update GoReleaser version to support the new builds
* add build option for arm64
> Enable Builds for arm64

- internal/git/git.go
- internal/git/git_integration_test.go
Make it easier to find out why extinction searches are timing out for some github action runs.
> Add additional debugging for extinction events

- build/metadata/github-actions/README.md
bumps `actions/checkout` to `v3` in examples
> bump checkout action in example

- docs/CONFIGURATION.md
- options/flags.go
- options/options.go
Allow `--repoType gitlab` during validation
App support to follow https://github.com/launchdarkly/gonfalon/pull/21002
> [sc-164648] add gitlab as acceptable repo type

- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/circleci/orb.yml
- build/package/github-actions/github-actions.go
- coderefs/coderefs.go
- flags/flags.go
- internal/helpers/user-agent.go
- internal/ld/ld.go
- options/flags.go
- options/options.go
Example:
`LDFindCodeRefs/2.5.7 (CI github-actions)`
Caveat: it's an optional CLI parameter, so we can't require it when used with docker image (gitlab) or directly with tool
> [sc-45912] Add CI tool to request user agent

- internal/git/git.go
logs recently added had no valuable content
```
6 251 185 193 128 214 233 125 161 221 107] 0x14000288f00 map[] map[]}) {orb.yml %!s(filemode.FileMode=33188) ysC? ?:?$?p~?">?tf?@}}} and to file: &{{build/package/circleci/orb.yml %!s(*object.Tree=&{[{orb.yml 33188 [64 23 115 209 204 254 247 200 124 99 55 113 53 176 237 71 42 150 196 141]}] [224 246 88 39 167 159 99 193 176 41 71 112 93 77 209 61 202 31 4 0] 0x14000288f00 map[] map[]}) {orb.yml %!s(filemode.FileMode=33188) @s?????|c7q5??G*?č}}}
DEBUG: 2022/08/31 16:04:18 git.go:218: Examining from file: &{{internal/version/version.go %!s(*object.Tree=&{[{version.go 33188 [233 201 27 89 79 206 135 168 45 212 35 155 98 161 188 66 1 22 37 20]}] [36 24 226 95 157 198 87 139 32 65 59 105 63 121 222 190 129 27 210 36] 0x14000288f00 map[] map[]}) …
```
> update debug logging for extinctions

- build/metadata/github-actions/README.md
tool that generates github action docs always includes "input" heading and the text can't be customized
> remove additional heading

- aliases/alias.go
- aliases/alias_test.go
- search/matcher_test.go
[Starting in v2.4.0](https://github.com/launchdarkly/ld-find-code-refs/pull/173), we throw an error if an alias filepattern glob has no matches. This reverts that behavior and we now just log when there are no matching files.
> Log when no files match alias file pattern

- aliases/alias.go
- aliases/alias_test.go
- search/matcher_test.go
Reverts launchdarkly/ld-find-code-refs#271 so we can attempt a v2.6.3 release
> Temporary revert "Log when no files match alias file pattern"

- internal/helpers/helpers.go
- internal/ld/ld.go
workflows with newer tokens set up were failing
> lock API version

- aliases/alias.go
- aliases/alias_test.go
- aliases/testdata/wild/nested-wild/alias_test.txt
- go.mod
- go.sum
- vendor/github.com/bmatcuk/doublestar/v4/.codecov.yml
- vendor/github.com/bmatcuk/doublestar/v4/.gitignore
- vendor/github.com/bmatcuk/doublestar/v4/LICENSE
- vendor/github.com/bmatcuk/doublestar/v4/README.md
- vendor/github.com/bmatcuk/doublestar/v4/UPGRADING.md
- vendor/github.com/bmatcuk/doublestar/v4/doublestar.go
- vendor/github.com/bmatcuk/doublestar/v4/glob.go
- vendor/github.com/bmatcuk/doublestar/v4/globoptions.go
- vendor/github.com/bmatcuk/doublestar/v4/globwalk.go
- vendor/github.com/bmatcuk/doublestar/v4/match.go
- vendor/github.com/bmatcuk/doublestar/v4/utils.go
- vendor/github.com/bmatcuk/doublestar/v4/validate.go
- vendor/modules.txt
use [doublestar](https://github.com/bmatcuk/doublestar) lib for glob
enable aliases like
```yaml
aliases: 
type: filepattern
name: "go aliases"
paths: 
- "**/*.go"
patterns: 
- "export const (\\w+) = flagPredicate\\(\\s*'FLAG_KEY'"
```
> [sc-169181] code refs alias file patterns support doublestar in globs

- build/metadata/bitbucket/README.md
- build/metadata/bitbucket/pipe.yml
Address additional feedback from [bitbucket team](https://bitbucket.org/bitbucketpipelines/official-pipes/pull-requests/519/update-launchdarkly-pipe#comment-345449796)
- remove env variables without default values from pipe
- `LD_DELIMITERS` was deprecated some time again, remove it
- `LD_PROJ_KEY` not required 100% of the time
> Update Bitbucket pipe metadata

- aliases/alias.go
- aliases/alias_test.go
- build/package/github-actions/github-actions.go
- internal/ld/ld.go
- internal/log/log.go
this package has been deprecated since Go 1.16 and started throwing lint errors.
> migrate deprecated ioutil pkg functions

- options/options.go
Our docs already indicate that dir should not be required.
> [sc-183433] subdir is not required for monorepo projects config

- build/package/circleci/orb.yml
Fixes https://github.com/launchdarkly/ld-find-code-refs/issues/322
https://support.circleci.com/hc/en-us/articles/360048353271-Accessing-BASH-ENV-Results-in-No-such-file-or-directory-
> CircleCI: make sure $BASH_ENV exists

- .github/workflows/gosec.yml
https://launchdarkly.atlassian.net/browse/SEC-2664
As part of our Repository Standards we need to run static analysis on all of our critical repositories.
This github action runs gosec against the repository and uploads the results to an S3 bucket.
This is intended to be a NON-BLOCKING action.
> Add Gosec github action

- build/package/circleci/orb.yml
Typo in `allowTags` parameter causes orb to fail.
> Fix typo in CircleCI orb

- internal/git/git.go
- search/matcher.go
1. This applies [Aho-Corasick algorithm used elsewhere](https://github.com/launchdarkly/ld-find-code-refs/pull/174) to scanning extinctions
2. It also changes extinction scanning so that it's _per file_ (so it can use the right matcher when monorepo is set up) instead of scanning the entire patch at once.
--
More context -
We have encountered a lot of slow extinctions runs that takes code refs scanning from 1-2 minutes to much longer.
One reason for this was a bug we introduced in 2.5.0, but even with the behavior restored, extinction checking can take a really long time and we often advise customer to set a low `lookback` (default is 10) to make runs faster.
This should dramatically speed up extinction checks and make code refs work better out of the box.
--
so fast 😍 
from this...
``` …
```
> Use Aho-Corasick implementation to speed up searching for extinctions

- internal/git/git.go
For annotated tags, we need to check the [target `ref`](https://pkg.go.dev/github.com/go-git/go-git/v5@v5.5.2/plumbing/object#Tag) instead of ref of tag object
Fixes https://github.com/launchdarkly/ld-find-code-refs/issues/329
> fix: failed to find tag name for annotated tags

- aliases/alias.go
- aliases/alias_test.go
- build/package/bitbucket-pipelines/bitbucket-pipelines.go
- build/package/bitbucket-pipelines/bitbucket-pipelines_test.go
- build/package/github-actions/github-actions.go
- build/package/github-actions/github-actions_test.go
- cmd/ld-find-code-refs/main.go
- coderefs/coderefs.go
- coderefs/coderefs_test.go
- flags/flags.go
- flags/flags_test.go
- go.mod
- internal/git/git.go
- internal/git/git_integration_test.go
- internal/helpers/helpers.go
- internal/helpers/user-agent.go
- internal/ld/ld.go
- internal/ld/ld_test.go
- options/options.go
- search/files.go
- search/matcher.go
- search/search.go
- search/search_test.go
module path should be updated for v2+
> module-path
The module's module path, usually the repository location from which the module can be downloaded by Go tools. For module versions v2 and later, this value must end with the major version number, such as /v2.
- [docs](https://go.dev/doc/modules/gomod-ref)
--
test with 
```
go get github.com/launchdarkly/ld-find-code-refs/v2@c5029a63b4da2a6ff9efbf63b400b16eff343d6c
```
> Update module-path to v2

- .circleci/config.yml
- .goreleaser.yml
- Makefile
Update:
More reliable build & build test CI
Specifics:
1. CI goreleaser version didn't match version used by release command
2. Update to latest version of goreleaser to fix [darwin/arm64](https://goreleaser.com/deprecations/#builds-for-darwinarm64) and [windows/arm64](https://goreleaser.com/deprecations/#builds-for-windowsarm64) deprecation warnings
3. Use new template format without [replacements](https://goreleaser.com/deprecations/#nfpmsreplacements)
4. [brews.tap](https://goreleaser.com/deprecations/#brewstap) is deprecated
5. --rm-dist is now --clean
> [sc-212684] update goreleaser and configuration

- .goreleaser.yml
Fix extra space before version in [text template](https://pkg.go.dev/text/template)
Confirmed fixed here: https://app.circleci.com/pipelines/github/launchdarkly/ld-find-code-refs/951/workflows/6488d332-5a17-4730-9f3a-6e0e2a5c5e3c/jobs/3343
> fix: incorrect names for some release assets

- search/matcher_test.go
Demonstrate delimiter behavior described in https://github.com/launchdarkly/ld-find-code-refs/issues/393
> test: example with delimiters disabled

- aliases/alias_test.go
fix in [strcase dependency](https://github.com/launchdarkly/ld-find-code-refs/pull/365) properly converts screaming snake case to camelcase
`MY_FLAG` to `myFlag`
> test: demonstrate alias conversion

- README.md
We moved some docs content around awhile ago, leaving some weird headings w/content in the readme - it's been multiple years, so I feel we can safely remove them.
This also revises the configuration section with links to relevant `/docs` files.
> docs: remove old docs

- aliases/alias.go
- aliases/types.go
Exposes functions for generating aliases so that other package can use them
See https://github.com/launchdarkly/find-code-references-in-pull-request/pull/71
> feat: expose alias generator functions

- search/delimiters.go
- search/element_matcher.go
- search/matcher.go
- search/scan.go
Reorg package to make it easier to understand.
Expose delimiters function and dedupe returned list.
Expose a function to make multi-project matcher from config (this is used for multi-repo support)
No functional or breaking changes.
> chore: reorganize search package

- build/metadata/github-actions/README.md
- build/metadata/github-actions/action.yml
- build/package/github-actions/github-actions.go
- coderefs/coderefs.go
- docs/CONFIGURATION.md
- options/flags.go
- options/options.go
Summary
1. allow pruning step to be skipped in code refs job
2. disable pruning by default in github action
more details
This will help silence ongoing error messages in GitHub Action until we are able to implement a suitable fix.
It's also just a good idea to allow this to be disabled in case a user has a reason for keeping old branches.
> [sc-223067] allow branch pruning to be disabled in main job

- flags/flags.go
- flags/flags_test.go
- Addresses issue #429.
- Projects without invalid flags will be ignored. A log message is written when this occurs.
> fix(#429): Multi-project scans now ignore projects without valid flags

- .ldrelease/publish-bitbucket-metadata.sh
- .ldrelease/publish-github-actions-metadata.sh
Make it easier when looking at commit messages to tell what version was being released
Also, create a major version tag which will allow users to get minor updates without manually updating their action file
```yaml
- uses: launchdarkly/find-code-references@v2
```
> chore: Add release version to commit message

- .github/workflows/main.yml
This is causing builds to fail because secrets are not passed through to workflows that run on forks (see Hosh's comment [here](https://launchdarkly.atlassian.net/browse/IDE-1459?focusedCommentId=323468))
We've got a bit of a backup going on with PRs in this repo. This change should help unblock them.
> dont publish junit tests on forks

- .github/workflows/release.yml
- scripts/release/commit-and-tag.sh
Another follow up for the migration to GHA from Releaser for this repo.
Releaser took care of updating the changelog, and I missed that I would need to include that in the GHA as well. The update will take place only after the release of the GHA, CircleCI Orb and BitBucket Pipe have completed successfully.
---
> [REL-4161] add logic to update the changelog

- scripts/release/commit-and-tag.sh
😩 please let this be the last one 😩
Using the heredoc was creating toil because the syntax is kinda fiddly and `workflow_dispatch` is only available on main, so I needed to create a PR and get a review for every change. But in the end, using `printf` is better anyway because it allows for backticks, which bash will try to run if they appear inside an unquoted heredoc. We'll see if the CHANGELOG comes out looking okay, but cursor assures me `printf` works well for multiline content. 🤞 
---
> [REL-4161] switch to printf to allow for backticks in CHANGELOG

- .github/workflows/release.yml
- scripts/release/commit-and-tag.sh
This update will fix the gross changelog formatting as long as the GHA changelog input is a single-line string with `\n` characters for new lines. Tested this out and it works.
---
> chore: [REL-4161] get changelog working with escaped string

- scripts/release/publish-dry-run.sh
- scripts/release/publish.sh
> chore: [REL-4161] fix typo

- .github/workflows/release.yml
This repo needs to access launchdarkly/homebrew-tap. See error [here](https://github.com/launchdarkly/ld-find-code-refs/actions/runs/16570352835/job/46860634653#step:7:642). Corresponding [terraform update](https://github.com/launchdarkly/terraform/pull/19909) (needs to be merged first). 
---
> chore: [REL-4161] add homebre-tap to repo_keys_map

- .github/workflows/release.yml
Missed a trailing comma that's causing things to blow up.
---
> chore: [REL-4161] remove trailing comma

- .github/workflows/release.yml
- Makefile
- scripts/release/stage-artifacts.sh
Okay, I think I finally understand why Goreleaser wasn't able to find the HOMEBREW_GH_TOKEN. Setting it as an env var on the GHA is not enough, it needs to be explicitly passed to the Makefile, and then passed to the Goreleaser command.
---
> chore: [REL-4161] pass homebrew token through Makefile to Goreleaser

- .github/workflows/release.yml
Deploy keys are apparently multi-line and need to be run through toJSON for proper encoding.
---
> chore: [REL-4161] run homebrew deploy key through toJSON

- scripts/release/publish.sh
Homebrew formula was updated successfully! The GHA bombed out on an unrelated (and easily fixed) problem where the `~/.ssh` folder already existed, but we tried to create it. Just need a `-p` there and we should be good to go. I think this may _actually_ be the last one!
Note: According to cursor, Goreleaser will either compare the binaries of the homebrew formula and determine that they are identical and skip the release, OR it will overwrite the homebrew formula with the new one (which is really just the same one). So in either case, we should be good to go there. I don't expect any weirdness. The rest of the action is idempotent, but it didn't run yet anyway, so no worries there either.
---
Related Jira issue: [REL-4161: Migrate ld-find-code-refs from Releaser to …
> chore: [REL-4161] dont bomb out if ssh dir exists

- scripts/release/targets/bitbucket.sh
- scripts/release/targets/gha.sh
There was a missing line here to get into the correct directory. This was just an oversight [^1]. However, the error was quite alarming, and it turns out there's some less-than-ideal git practices here that I'll definitely be cleaning up once I finally get this release out the door. The tl;dr is that we have the main coderefs tool that lives in this repo and we have two other repos that contain the coderefs GHA and the coderefs Bitbucket Pipe. As it happens, we are cloning those repos into directories _inside_ the main repo. This seems like a very bad idea, and I can't imagine any possible benefit from doing that. Anyway, in this case, since the `cd githubActionsMetadataUpdates` line was missing, I was still in the `ld-find-code-refs` repo (where the 2.14.0 tag had already been created), …
> chore: [REL-4161] ensure tag is being created in the correct directory

- scripts/release/targets/circleci.sh
Orb check caused the action to [fail](https://github.com/launchdarkly/ld-find-code-refs/actions/runs/16807638943/job/47604213552#step:7:679) last time. The way we were doing the check was not great as it pulls every single public Orb and greps for the coderefs orb with the version we're looking for. I tried that locally and verified that it doesn't find the orb (even though it exists). I also tried the updated orb check locally, which is way more efficient and does find the Orb we're looking for.
---
> chore: [REL-4161] make the circleci orb check more reliable

- .github/workflows/release.yml
The GITHUB_TOKEN that's built-in to the GHA is not authorized to push directly to main. We need to do this in order to push up our committed changes to the remote repo so we can create the release. I had a new SSM parameter added that will allow this, so we should be able to cut the release now with this new token. I needed to get a little creative since the value is not known until after the `get secrets` step runs, but I think what I have here should work.
---
> chore: [REL-4161] use elevated token for git stuff
