launchdarkly/ld-find-code-refs

CHANGELOG.md, parse/parse.go, parse/parse_test.go
After 500 characters, truncate lines.
=> Add a line length limit.

README.md, build/package/circleci/orb.yml
Various doc improvements. Most notably, added a separate section for examples (with more examples)
=> Documentation updates

CHANGELOG.md, README.md, build/package/circleci/orb.yml, internal/version/version.go
=> Prepare 1.0.0

.circleci/config.yml, build/package/github-actions/Dockerfile
As discussed in Slack and co-authored by Mira.
=> add github actions labels for marketplace submission

build/package/bitbucket-pipelines/bitbucket-pipelines.go, build/package/github-actions/github-actions.go, internal/log/log.go, pkg/coderefs/coderefs.go
Adds a call to action to file a github issue when a user encounters an unrecoverable fatal error
=> add fatal logger message

internal/command/command.go, pkg/coderefs/coderefs.go, pkg/coderefs/coderefs_test.go
zero-sum change to make variable names more generic
=> rename variables referencing grep

coderefs/alias.go, coderefs/alias_test.go, coderefs/testdata/wild/alias_test.txt
=> fix path handling for glob patterns

.circleci/config.yml
CI is failing without this change.
=> Updating from python-pip to python3-pip

CHANGELOG.md, build/package/circleci/orb.yml, internal/version/version.go
Update version numbers for new release.
=> Update code refs version

.circleci/config.yml
Reverts launchdarkly/ld-find-code-refs#164
=> Revert "Add docker login"

CODEOWNERS
=> add DX as codeowners for reviews

search/matcher_test.go
Adds unit tests for Matcher function
=> Add matcher tests

coderefs/coderefs.go
We do not currently have testing covering this. Will add a followup ticket for that.
=> Do not run extinctions with dry run

build/package/github-actions/github-actions.go
- return early to make function more readable
- update error message to only show tags
ref in message when allowTags is true
=> Refactor event parsing

coderefs/coderefs.go, internal/git/git.go, internal/ld/ld.go
We current support timestamp but it is unused. Additional updates will be needed server side, this is first step.
=> Add timestamp of commit

coderefs/coderefs.go, flags/flags.go, search/matcher.go
Make the errors cleaner per project. Also add additional information around options for sending too large of a payload
=> Clean up errors

build/metadata/github-actions/README.md
Add concurrency control for the github action and additional examples excluding dependabot
=> Update Github Action Examples

.ldrelease/run-publish-target.sh
Update build command to pass in Github token.
=> Pass in github token

build/package/bitbucket-pipelines/bitbucket-pipelines.go, build/package/github-actions/github-actions.go, cmd/ld-find-code-refs/main.go, coderefs/coderefs.go, internal/ld/ld.go, internal/ld/ld_test.go
* Add parameter to `Run` to determine if it should output the flag search(POST or generate CSV). This allows for new manual command to run extinctions only
* fix extinction bug related to count
* update test
=> Fix only searching for a single extinction per project

.gitignore, .ldrelease/publish-bitbucket-metadata.sh, .ldrelease/publish-github-actions-metadata.sh, .ldrelease/publish.sh, .ldrelease/secrets.properties
Adding bitbucket creds to automate publishing to bitbucket repo for coderefs pipe.
=> [sc 137708] Add bitbucket creds

.ldrelease/publish-bitbucket-metadata.sh, .ldrelease/publish-github-actions-metadata.sh, .ldrelease/run-publish-target.sh
=> Changes for Release

search/search.go, search/search_test.go
* update truncateLine to count runes
* truncateLine maxCharCount is configurable
* add test cases
=> Fixes slice bounds out of range error

README.md
Adds notes about compiling with FIPS 140-2 support
=> Add documentation for federal users

build/metadata/bitbucket/README.md, build/metadata/github-actions/README.md, build/package/circleci/orb.yml, build/package/github-actions/github-actions_test.go, coderefs/coderefs_test.go, docs/CONFIGURATION.md, internal/ld/ld_test.go, options/flags.go
`defaultBranch` fallback value is "main"
=> [sc-154212] update default branch name to main

build/package/circleci/orb.yml, docs/CONFIGURATION.md, options/flags.go
- circle ci orb
- alphabetize repo type options
=> [sc-164648] update more repo type info with gitlab

internal/git/git.go
Hoping that this will help in resolving issue w/new versions of git.
```
ERROR: 2022/08/31 18:27:52 coderefs.go:37: error parsing current commit sha: fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:
git config --global --add safe.directory /github/workspace
```
=> [sc-135747] use go git library for all git commands

.ldrelease/publish-bitbucket-metadata.sh, .ldrelease/publish-github-actions-metadata.sh
This is the Release bot user that creates releases etc
https://github.com/LaunchDarklyReleaseBot
=> [sc-144002] update git user info for commits

aliases/alias.go, aliases/alias_test.go, search/matcher_test.go
Reverts launchdarkly/ld-find-code-refs#276
=> Revert "Temporary revert "Log when no files match alias file pattern""

.circleci/config.yml, .golangci.yml, .ldrelease/config.yml, .pre-commit-config.yaml, Dockerfile.bitbucket, Dockerfile.github, build/package/cmd/Dockerfile, build/package/github-actions/github-actions.go, coderefs/coderefs.go, docs/TESTING.md, flags/flags.go, options/options.go
- bumped go version in circleci
- bumped docker file versions
- had to update from precommit rules
- had to change install strategy for test deps in circleci workflow
=> update go and docker image versions

build/metadata/github-actions/README.md
update causes readme to change which is blocking other PRs
=> update action-docs to 1.1.0

go.mod, go.sum
https://github.com/sergi/go-diff/issues/117
=> bump go-diff version to 1.2.0

build/metadata/bitbucket/README.md, build/metadata/bitbucket/pipe.yml
=> Update bitbucket docs

internal/git/git.go
There was a logic issue that was causing a commit diff patch to be scanned multiple times - once for each changed file in the commit.
Bug introduced in [2.5.0](https://github.com/launchdarkly/ld-find-code-refs/releases/tag/2.5.0)
=> Fix: extinctions scans take hours

docs/ALIASES.md
Include commands for making a file executable when adding to git
=> add more info about executable alias files

.golangci.yml, aliases/alias.go, cmd/ld-find-code-refs/main.go, internal/git/git.go, options/alias.go, options/options.go
- move generating aliases from filepattern and command into functions
- clean up the extinctions scanning
- clean up err handling
=> [sc-211678] enable funlen check and refactor functions

.goreleaser.yml
https://github.com/launchdarkly/homebrew-tap
=> update commit author for brew

.ldrelease/secrets.properties
=> chore: update path to orb token

build/metadata/github-actions/README.md
to latest v4 https://github.com/actions/checkout/releases
=> chore: bump actions/checkout version in example

aliases/alias.go, aliases/alias_test.go, aliases/aliases-test.py
Adds examples for pascalcase and command
=> test: add alias tests that can be used as examples

docs/ALIASES.md
Track issue in viper: https://github.com/spf13/viper/issues/1014
=> docs: add note about literal alias limitation

internal/ld/ld.go
Update archived api call to use new state filter
=> update requests made to use 'state' filter; request deprecated flags

build/metadata/github-actions/README.md
GitHub action docs will link to configuration docs.
=> docs: add links to configuration

scripts/release/commit-and-tag.sh
Hopefully this will be the last one 😅.
Yesterday evening I added the CHANGELOG update which I had overlooked initially because Releaser did it behind-the-scenes. But there was an extra `)` in the code 🤦, so that's fixed here, and I'm also logging out the changelog so future releasers will be able to see the diff and the updated CHANGELOG when they run a dry run or actual release. There's also a minor refactor here. It's nothing big, but it makes the updates a bit harder to grok, so I'll try to comment in the code to explain what was changed.
---
=> [REL-4161] fix syntax error; add a bit more logging

.github/workflows/release.yml, scripts/release/commit-and-tag.sh
debugging the changelog issues
---
=> chore: [REL-4161] debugging changelog
